apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app: guestbook-ui
